#!/bin/bash -xe

# FIXME: remove this hack once the new staging_dir structure changes get merged from trunk
mimic_new_staging_dir_host ()
{
    mkdir -p staging_dir/target-arm_cortex-a9+vfpv3_musl-1.1.11_eabi || true
    ln -sf ../host staging_dir/target-arm_cortex-a9+vfpv3_musl-1.1.11_eabi/host
}

# Cleaning
rm -rf ./tmp ./bin ./logs*
[ -z "$BUILD_ALL" ] || make dirclean

# Clean feeds
./scripts/feeds clean

# Install feeds
./scripts/feeds update -a
./scripts/feeds install -a

# Uninstall eudev - conflicts with udev
./scripts/feeds uninstall eudev

# Build FW
cp configs/config-omnia .config
[ -n "$BUILD_ALL" ] && echo "CONFIG_ALL=y" >> .config && echo "CONFIG_SDK=y" >> .config
[ -n "$USE_CCACHE" ] && echo "CONFIG_CCACHE=y" >> .config
make defconfig
export TARGET_BOARD=omnia
if [ -d .git ] ; then
	git log -n1 --format='%H' >files/etc/git-version
fi
make clean
mimic_new_staging_dir_host
make "$@"
mv ./logs ./logs-nand

# Build initramfs
echo -e "CONFIG_TARGET_ROOTFS_INITRAMFS=y\nCONFIG_TARGET_INITRAMFS_COMPRESSION_XZ=y" >> .config
make defconfig
make target/linux/compile "$@"
mv ./logs ./logs-initram
cp build_dir/target-arm_*/linux-mvebu/zImage-initramfs bin/mvebu-musl/omnia-initramfs-zimage

# Preserve the uncompressed image too
mv build_dir/target-arm_*/root-mvebu bin/mvebu-musl/root
cd bin/mvebu-musl/root
rm var
find -type l ! -exec test -r {} \; -delete
cd ../../..

# Clean
rm -rf ./bin-nand
mv ./bin ./bin-nand
rm -rf ./tmp
