#!/bin/bash -xe

# Cleaning
rm -rf ./tmp ./bin ./logs*

# Clean feeds
./scripts/feeds clean

# Install feeds
./scripts/feeds update -a
./scripts/feeds install -a

# Build FW
cp configs/config-omnia .config
[ -n "$BUILD_ALL" ] && echo "CONFIG_ALL=y" >> .config && echo "CONFIG_SDK=y" >> .config
[ -n "$USE_CCACHE" ] && echo "CONFIG_CCACHE=y" >> .config
make defconfig
export TARGET_BOARD=omnia
if [ -d .git ] ; then
	git log -n1 --format='%H' >files/etc/git-version
fi
make clean
make "$@"
mv ./logs ./logs-nand

# Build initramfs
echo -e "CONFIG_TARGET_ROOTFS_INITRAMFS=y\nCONFIG_TARGET_INITRAMFS_COMPRESSION_XZ=y" >> .config
make defconfig
make target/linux/compile "$@"
mv ./logs ./logs-initram
cp build_dir/target-arm_*/linux-mvebu/zImage-initramfs bin/mvebu-musl/omnia-initramfs-zimage

# Preserve the uncompressed image too
mv build_dir/target-arm_*/root-mvebu bin/mvebu-musl/root
cd bin/mvebu-musl/root
rm var
find -type l ! -exec test -r {} \; -delete
cd ../../..

# Clean
rm -rf ./bin-nand
mv ./bin ./bin-nand
rm -rf ./tmp
