#!/bin/bash -xe

# Cleaning 
[ -d ./tmp ] && rm -rf ./tmp
[ -d ./bin ] && rm -rf ./bin

# Clean feeds
./scripts/feeds clean

# Install luci feed
./scripts/feeds update -a
./scripts/feeds install -a

# Uninstall broken pkgs
for pkg in $(cat ./disabled_packages); do ./scripts/feeds uninstall $pkg; done

# Build NAND FW
cp configs/config-turris-nand .config
[ -n "$BUILD_ALL" ] && echo "CONFIG_ALL=y" >> .config && echo "CONFIG_SDK=y" >> .config
[ -n "$USE_CCACHE" ] && echo "CONFIG_CCACHE=y" >> .config
make defconfig
export TARGET_BOARD=turris
if [ -d .git ] ; then
	git log -n1 --format='%H' >files/etc/git-version
fi
make clean
make "$@"

#Build initramfs
echo -e "CONFIG_TARGET_ROOTFS_INITRAMFS=y\nCONFIG_TARGET_INITRAMFS_COMPRESSION_XZ=y" >> .config
make defconfig
make target/linux/compile "$@"
cp build_dir/target-powerpc_*/linux-mpc85xx_p2020-nand/zImage-initramfs bin/mpc85xx/turris-initramfs-zimage

# Preserve the uncompressed image too
mv build_dir/target-powerpc_*/root-mpc85xx bin/mpc85xx/root
cd bin/mpc85xx/root
rm var
find -type l ! -exec test -r {} \; -delete
cd ../../..

# Clean
[ -d ./bin-nand ] && rm -rf ./bin-nand
mv ./bin ./bin-nand
[ -d ./tmp ] && rm -rf ./tmp

# Build NOR FW
cp configs/config-turris-nor .config
[ -n "$USE_CCACHE" ] && echo "CONFIG_CCACHE=y" >> .config
make defconfig
make clean
make "$@"
[ -d ./bin/mpc85xx/packages ] && rm -rf ./bin/mpc85xx/packages
[ -d ./bin-nor ] && rm -rf ./bin-nor
mv ./bin ./bin-nor


