#!/bin/bash -xe

# Prevent the auto-appearence of menuconfig
cp configs/config-turris-nand .config
make defconfig

[ -f ./Makefile ] && make clean || true
[ -d ./tmp ] && rm -rf ./tmp
[ -d ./bin ] && rm -rf ./bin

# Build u-boot
./compile_u-boot

# Install luci feed
./scripts/feeds update lucics
./scripts/feeds install luci
./scripts/feeds install luci-i18n-czech

# Install routing feed and bird package
./scripts/feeds update routing
./scripts/feeds install bird4 birdc4 bird6 birdc6

# Build NAND FW
cp configs/config-turris-nand .config
[ -n "$BUILD_ALL" ] && echo "CONFIG_ALL=y" >> .config
[ -n "$USE_CCACHE" ] && echo "CONFIG_CCACHE=y" >> .config
make defconfig
export TARGET_BOARD=turris
./set_opkg_url
if [ -d .git ] ; then
	git log -n1 --format='%H' >files/etc/git-version
fi
make clean
make "$@"

# Clean
[ -d ./bin-nand ] && rm -rf ./bin-nand
mv ./bin ./bin-nand
[ -d ./tmp ] && rm -rf ./tmp

# Build NOR FW
cp configs/config-turris-nor .config
[ -n "$USE_CCACHE" ] && echo "CONFIG_CCACHE=y" >> .config
make defconfig
make clean
make "$@"
[ -d ./bin/mpc85xx/packages ] && rm -rf ./bin/mpc85xx/packages
[ -d ./bin-nor ] && rm -rf ./bin-nor
mv ./bin ./bin-nor


