# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  if ENV["PROCESSOR_ARCHITECTURE"] == "x86"
    puts "Host seems to be 32-bit system, please use Vagrantfile for VirtualBox"
    exit
  end

  config.vm.box = "fgrehm/trusty64-lxc"

  # system's hostname
  config.vm.hostname = "turris-buildroot"

  # link working directory to /openwrt in guest system
  config.vm.synced_folder ".", "/openwrt"

  # Enable SSH agent forwarding - useful when checking out Git repositories
  config.ssh.forward_agent = true

  # Main provisioning script
  config.vm.provision "shell", path: "vagrant/vagrant_provision.sh", args: "install_bashcompletion"

  # Uncomment the following block if you have older LXC (for example 0.7.5 in Ubuntu 12.04)
  # Vagrant.configure("2") do |config|
  #   config.vm.provider :lxc do |lxc|
  #     lxc.backingstore = 'none'
  #   end
  # end
end
