#!/bin/sh /etc/rc.common
# Copyright (C) 2016 CZ.NIC

START=25

start() {
	# Update WiFi LED configuration
	cd /sys/devices/platform/soc/soc:pcie-controller/pci0000:00/
	for i in `uci show system | sed -n 's|.*\.@led\[\([0-9][0-9]*\)\]\..*|\1|p' | uniq`; do
		NAME="`uci get system.@led[$i].name`"
		PCI="`echo "$NAME" | sed -n 's|Auto-configuration for PCI\([1-3]\)|\1|p'`"
		[ -n "$PCI" ] || continue
		REAL_PCI="`expr 4 - $PCI`"
		PHY="`ls -d 0000:00:0${REAL_PCI}.0/0000:0${REAL_PCI}:00.0/ieee80211/phy* 2> /dev/null | sed -n 's|.*/\(phy[0-9]\)|\1|p'`"
		DEV="`ls -d 0000:00:0${REAL_PCI}.0/0000:0${REAL_PCI}:00.0/ieee80211/phy*/device/net/wlan* | sed 's|.*/||'`"
		uci set system.@led[$i].sysfs="omnia-led:pci$PCI"
		if [ "$PHY" ]; then
			 uci set system.@led[$i].default="1"
			 uci set system.@led[$i].trigger="netdev"
			 uci set system.@led[$i].dev="$DEV"
			 uci set system.@led[$i].mode="link tx rx"
		else
			 uci set system.@led[$i].default="0"
			 uci set system.@led[$i].trigger="none"
			 uci delete system.@led[$i].dev 2> /dev/null
			 uci delete system.@led[$i].mode 2> /dev/null
		fi
		uci commit system
	done
	# Update SATA ocnfiguration
	cd /sys/devices/platform/soc
	MSATA="`ls soc\:internal-regs/*.sata/ata*/host*/target*/*0*/block`"
	if [ "$MSATA" ]; then
		for i in `uci show system | sed -n 's|.*\.@led\[\([0-9][0-9]*\)\]\..*|\1|p' | uniq`; do
			NAME="`uci get system.@led[$i].name`"
			PCI="`echo "$NAME" | sed -n 's|Auto-configuration for PCI\([1-3]\)|\1|p'`"
			[ -n "$PCI"    ] || continue
			[ "$PCI" -eq 3 ] || continue
			uci set system.@led[$i].default="0"
			uci set system.@led[$i].trigger="${MSATA}"
			uci delete system.@led[$i].dev 2> /dev/null
			uci delete system.@led[$i].mode 2> /dev/null
		done
	fi
}
