#!/bin/sh /etc/rc.common
# Copyright (C) 2013-2014 OpenWrt.org

START=00

boot() {
	local hwtime=0
	if [ -c /dev/rtc0 ]; then
		hwtime=$(/bin/busybox date +%s -d"$(hwclock -r -u -f /dev/rtc0)" -D"%a %b %d %H:%M:%S %Y  0.000000 seconds")
	fi
	if [ -z $hwtime ] || [ $hwtime -lt 1420424242 ]; then
		# hwtime is broken, approximate from /etc files
		local curtime="$(/bin/busybox date +%s)"
		local maxtime="$(find /etc -type f -exec date -r {} +%s \; | sort -nr | head -n1)"
		[ $curtime -lt $maxtime ] && /bin/busybox date -s @$maxtime
		# write "better" time to RTC if it's present
		if [ -c /dev/rtc0 ]; then
			hwclock -u -w -f /dev/rtc0
		fi
	else
		hwclock -u -s -f /dev/rtc0
	fi
}
