#!/bin/sh
for file in `grep -Rl DEPENDS.*libpcap package/`; do
	NUM="`sed -n 's|.*PKG_RELEASE[^0-9]*\([0-9]*\)$|\1|p' "$file"`"
	NEXT_NUM="`expr $NUM + 1`"
	[ -z "$NEXT_NUM" ] || echo "$file $NUM $NEXT_NUM" >> release-override
done
